spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.q0i6n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Member


